### ISSUE TITLE
zerovert-qt-64-linux throws segfault on existing data directory

### ISSUE THREAD

**Issue by doetsch** [Zerovert/Zerovert#1]
First start of zerovert-qt-64-linux is successful and blockchain syncs completely. After shutting down the client and restarting it with the same data directory, the program shortly shows the splashscreen and then terminates with a segmentation fault.

OS: Linux Mint 17 64Bit

ldd ./zerovert-qt-64-linux
    linux-vdso.so.1 =>  (0x00007fff763e9000)
    libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fe8000e7000)
    libQtGui.so.4 => /usr/lib/x86_64-linux-gnu/libQtGui.so.4 (0x00007fe7ff434000)
    libQtNetwork.so.4 => /usr/lib/x86_64-linux-gnu/libQtNetwork.so.4 (0x00007fe7ff0eb000)
    libQtCore.so.4 => /usr/lib/x86_64-linux-gnu/libQtCore.so.4 (0x00007fe7fec06000)
    libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fe7fe902000)
    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fe7fe5fb000)
    libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fe7fe3e5000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fe7fe01f000)
    librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fe7fde16000)
    /lib64/ld-linux-x86-64.so.2 (0x00007fe800333000)
    libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007fe7fdbda000)
    libaudio.so.2 => /usr/lib/x86_64-linux-gnu/libaudio.so.2 (0x00007fe7fd9c2000)
    libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007fe7fd6b9000)
    libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x00007fe7fd493000)
    libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fe7fd27a000)
    libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007fe7fcfd6000)
    libgobject-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007fe7fcd85000)
    libSM.so.6 => /usr/lib/x86_64-linux-gnu/libSM.so.6 (0x00007fe7fcb7d000)
    libICE.so.6 => /usr/lib/x86_64-linux-gnu/libICE.so.6 (0x00007fe7fc960000)
    libXi.so.6 => /usr/lib/x86_64-linux-gnu/libXi.so.6 (0x00007fe7fc750000)
    libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007fe7fc546000)
    libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007fe7fc333000)
    libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007fe7fbffe000)
    libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fe7fbdf9000)
    libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007fe7fbbcf000)
    libXt.so.6 => /usr/lib/x86_64-linux-gnu/libXt.so.6 (0x00007fe7fb968000)
    libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007fe7fb764000)
    libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007fe7fb526000)
    libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007fe7fb31d000)
    libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007fe7fb118000)
    libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fe7faef8000)
    libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fe7facf2000)

**Comment by bushido** [comment]
Please use "-reindex" for awhile, we are finding the root caused.
